# Generated by Django 5.0.6 on 2024-07-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_alter_sampledata_address_alter_sampledata_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledata',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
