# Generated by Django 5.0.6 on 2024-07-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_alter_sampledata_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'APIkey',
            },
        ),
    ]
